"""apwobasyon tan travay

Revision ID: 8d8e33fa5923
Revises: 98fb226ac2ae
Create Date: 2026-09-24 18:26:50.381830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8e33fa5923'
down_revision: Union[str, None] = '98fb226ac2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pay_period_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'RETURNED', name='timesheetstatus'), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'pay_period_id', name='uq_timesheet_emp_period')
    )
    with op.batch_alter_table('timesheet_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheet_approvals_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheet_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheet_approvals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheet_approvals_pay_period_id'), ['pay_period_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheet_approvals_pay_period_id'))
        batch_op.drop_index(batch_op.f('ix_timesheet_approvals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_timesheet_approvals_id'))
        batch_op.drop_index(batch_op.f('ix_timesheet_approvals_employee_id'))

    op.drop_table('timesheet_approvals')
    # ### end Alembic commands ###
