"""kesyon fom aplikasyon

Revision ID: 98fb226ac2ae
Revises: 6a7914a087bf
Create Date: 2026-09-24 16:51:32.171232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fb226ac2ae'
down_revision: Union[str, None] = '6a7914a087bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('system_key', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('help_text', sa.String(length=500), nullable=True),
    sa.Column('question_type', sa.Enum('SHORT_TEXT', 'LONG_TEXT', 'YES_NO', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'NUMBER', 'DATE', 'URL', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('condition_question_id', sa.Integer(), nullable=True),
    sa.Column('condition_value', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['condition_question_id'], ['application_questions.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'system_key', name='uq_question_org_key')
    )
    with op.batch_alter_table('application_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_questions_job_posting_id'), ['job_posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_questions_organization_id'), ['organization_id'], unique=False)

    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_label', sa.String(length=300), nullable=False),
    sa.Column('question_type', sa.Enum('SHORT_TEXT', 'LONG_TEXT', 'YES_NO', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'NUMBER', 'DATE', 'URL', name='questiontype'), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['application_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'question_id', name='uq_answer_app_question')
    )
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_answers_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_answers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_application_answers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_application_answers_id'))
        batch_op.drop_index(batch_op.f('ix_application_answers_application_id'))

    op.drop_table('application_answers')
    with op.batch_alter_table('application_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_questions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_application_questions_job_posting_id'))
        batch_op.drop_index(batch_op.f('ix_application_questions_id'))

    op.drop_table('application_questions')
    # ### end Alembic commands ###
