"""
Konbit — Fich peye an PDF
Chemen: backend/app/payslip_pdf.py

Depandans: reportlab (pip install "reportlab>=4.2"). Li se Python pi:
pa gen anyen pou enstale sou Windows oswa sou Render anplis.

Polis estanda PDF yo (Helvetica) konn tout lèt kreyòl, franse ak angle
yo (ò, è, à, é…), kidonk pa gen okenn fichye polis pou mete nan repo a.
Etikèt yo egziste an kreyòl, franse ak angle — menm lang ak mesaj
backend yo (app/i18n.py). Lòt lang yo resevwa PDF la an angle.

Fonksyon sa a pa touche baz done a: routers/payroll.py ba l tout sa l
bezwen, sa ki fè l fasil pou teste.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from io import BytesIO
from typing import Optional
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

NAVY = colors.HexColor("#0b1f4b")
BLUE = colors.HexColor("#2563eb")
INK = colors.HexColor("#0f172a")
MUTED = colors.HexColor("#475569")
LINE = colors.HexColor("#d5dde8")
SOFT = colors.HexColor("#f1f5f9")
RED = colors.HexColor("#b91c1c")

LABELS: dict[str, dict[str, str]] = {
    "ht": {
        "title": "FICH PEYE",
        "period": "Peryòd",
        "pay_date": "Dat peman",
        "employee": "Anplwaye",
        "number": "Nimewo",
        "position": "Pozisyon",
        "nif": "NIF",
        "earnings": "Revni",
        "deductions": "Retni",
        "amount": "Montan",
        "rate": "To",
        "base": "Salè debaz",
        "overtime": "Èdtan siplemantè ({h} è)",
        "bonus": "Bonis",
        "gross": "Salè brit",
        "iri": "IRI — enpo sou salè",
        "supplemental": "Retni sou bonis / èdtan siplemantè",
        "other": "Lòt dediksyon",
        "total_ded": "Total retni",
        "net": "NET POU PEYE",
        "payment": "Peman",
        "check": "Chèk nimewo {n}",
        "check_plain": "Chèk",
        "deposit": "Depo dirèk",
        "cash": "Lajan kach",
        "status_paid": "Peye {date}",
        "status_approved": "Apwouve, poko peye",
        "status_draft": "Bouyon — pa valab pou peman",
        "watermark": "BOUYON",
        "generated": "Dokiman jenere pa KONMBIT {date}",
        "ref": "Fich #{id}",
    },
    "fr": {
        "title": "BULLETIN DE PAIE",
        "period": "Période",
        "pay_date": "Date de paiement",
        "employee": "Employé",
        "number": "Matricule",
        "position": "Poste",
        "nif": "NIF",
        "earnings": "Gains",
        "deductions": "Retenues",
        "amount": "Montant",
        "rate": "Taux",
        "base": "Salaire de base",
        "overtime": "Heures supplémentaires ({h} h)",
        "bonus": "Prime",
        "gross": "Salaire brut",
        "iri": "IRI — impôt sur le revenu",
        "supplemental": "Retenue sur primes / heures supp.",
        "other": "Autres retenues",
        "total_ded": "Total des retenues",
        "net": "NET À PAYER",
        "payment": "Paiement",
        "check": "Chèque n° {n}",
        "check_plain": "Chèque",
        "deposit": "Virement bancaire",
        "cash": "Espèces",
        "status_paid": "Payé le {date}",
        "status_approved": "Approuvé, pas encore payé",
        "status_draft": "Brouillon — non valable pour paiement",
        "watermark": "BROUILLON",
        "generated": "Document généré par KONMBIT le {date}",
        "ref": "Bulletin n° {id}",
    },
    "en": {
        "title": "PAYSLIP",
        "period": "Period",
        "pay_date": "Payment date",
        "employee": "Employee",
        "number": "Employee no.",
        "position": "Position",
        "nif": "Tax ID",
        "earnings": "Earnings",
        "deductions": "Deductions",
        "amount": "Amount",
        "rate": "Rate",
        "base": "Base salary",
        "overtime": "Overtime ({h} h)",
        "bonus": "Bonus",
        "gross": "Gross pay",
        "iri": "IRI — income tax",
        "supplemental": "Withholding on bonus / overtime",
        "other": "Other deductions",
        "total_ded": "Total deductions",
        "net": "NET PAY",
        "payment": "Payment",
        "check": "Check no. {n}",
        "check_plain": "Check",
        "deposit": "Direct deposit",
        "cash": "Cash",
        "status_paid": "Paid on {date}",
        "status_approved": "Approved, not paid yet",
        "status_draft": "Draft — not valid for payment",
        "watermark": "DRAFT",
        "generated": "Document generated by KONMBIT on {date}",
        "ref": "Payslip #{id}",
    },
}


@dataclass
class PayslipDoc:
    """Tout sa PDF la bezwen. Montan yo an santim."""
    lang: str
    slip_id: int
    status: str                     # "draft" | "approved" | "paid"
    currency: str
    # Biznis
    org_name: str
    org_address: Optional[str]
    org_tax_id: Optional[str]
    # Anplwaye
    employee_name: str
    employee_number: str
    position_title: Optional[str]
    # Peryòd
    period_name: str
    start_date: date
    end_date: date
    pay_date: date
    paid_on: Optional[date]
    generated_on: date
    # Montan
    base_amount: int
    overtime_amount: int
    overtime_hours: float
    bonus_amount: int
    gross_amount: int
    tax_amount: int
    supplemental_tax_amount: int
    ona_amount: int
    ofatma_amount: int
    cfgdct_amount: int
    fdu_cas_amount: int
    other_deductions: int
    net_amount: int
    # To yo, pou kolòn "To" a (0.06 = 6%)
    supplemental_rate: float
    ona_rate: float
    ofatma_rate: float
    cfgdct_rate: float
    fdu_cas_rate: float
    # Peman
    payment_method: str             # check | direct_deposit | cash | moncash | natcash
    check_number: Optional[str]
    bank_name: Optional[str]
    account_last4: Optional[str]
    transaction_ref: Optional[str]


def _money(cents: int, lang: str) -> str:
    """3912500 → '39 125,00' (ht/fr) oswa '39,125.00' (en)."""
    value = f"{abs(cents) / 100:,.2f}"
    if lang in ("ht", "fr"):
        value = value.replace(",", "\u00a0").replace(".", ",")
    return ("-" if cents < 0 else "") + value


def _hours(h: float, lang: str) -> str:
    """12.5 → '12,5' (ht/fr) oswa '12.5' (en)."""
    text = f"{h:g}"
    return text.replace(".", ",") if lang in ("ht", "fr") else text


def _pct(rate: float) -> str:
    return f"{rate * 100:g}%"


def _date(d: Optional[date]) -> str:
    return d.strftime("%d/%m/%Y") if d else "—"


def _payment_text(doc: PayslipDoc, L: dict[str, str]) -> str:
    m = doc.payment_method
    if m == "check":
        return L["check"].format(n=doc.check_number) if doc.check_number else L["check_plain"]
    if m == "direct_deposit":
        parts = [L["deposit"]]
        if doc.bank_name:
            parts.append(doc.bank_name)
        if doc.account_last4:
            parts.append(f"••{doc.account_last4}")
        return " — ".join(parts)
    if m in ("moncash", "natcash"):
        name = "MonCash" if m == "moncash" else "NatCash"
        return f"{name} — {doc.transaction_ref}" if doc.transaction_ref else name
    if m == "cash":
        return L["cash"]
    return m


def render_payslip_pdf(doc: PayslipDoc, *, compress: bool = True) -> bytes:
    L = LABELS.get(doc.lang) or LABELS["en"]
    lang = doc.lang if doc.lang in LABELS else "en"
    cur = doc.currency

    s_small = ParagraphStyle("small", fontName="Helvetica", fontSize=8.5, leading=11, textColor=MUTED)
    s_body = ParagraphStyle("body", fontName="Helvetica", fontSize=9.5, leading=13, textColor=INK)
    s_bold = ParagraphStyle("bold", parent=s_body, fontName="Helvetica-Bold")
    s_org = ParagraphStyle("org", fontName="Helvetica-Bold", fontSize=14, leading=17, textColor=INK)
    s_title = ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=15, leading=18,
                             textColor=NAVY, alignment=TA_RIGHT)
    s_right = ParagraphStyle("right", parent=s_small, alignment=TA_RIGHT)

    def P(text: str, style=s_body) -> Paragraph:
        return Paragraph(escape(text), style)

    width = letter[0] - 36 * mm

    # --- Tèt: biznis la (goch) ak tit la (dwat) ---
    org_lines = [P(doc.org_name, s_org)]
    if doc.org_address:
        org_lines.append(P(doc.org_address, s_small))
    if doc.org_tax_id:
        org_lines.append(P(f"{L['nif']}: {doc.org_tax_id}", s_small))
    head = Table(
        [[org_lines, [P(L["title"], s_title), P(L["ref"].format(id=doc.slip_id), s_right)]]],
        colWidths=[width * 0.6, width * 0.4],
    )
    head.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("LINEBELOW", (0, 0), (-1, 0), 2, NAVY),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ]))

    # --- Anplwaye ak peryòd ---
    left = [
        [P(L["employee"], s_small), P(doc.employee_name, s_bold)],
        [P(L["number"], s_small), P(doc.employee_number)],
    ]
    if doc.position_title:
        left.append([P(L["position"], s_small), P(doc.position_title)])
    right = [
        [P(L["period"], s_small), P(doc.period_name, s_bold)],
        [P("", s_small), P(f"{_date(doc.start_date)} – {_date(doc.end_date)}")],
        [P(L["pay_date"], s_small), P(_date(doc.pay_date))],
    ]
    half = width / 2 - 4 * mm

    def kv(rows):
        t = Table(rows, colWidths=[half * 0.34, half * 0.66])
        t.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        return t

    info = Table([[kv(left), kv(right)]], colWidths=[width / 2, width / 2])
    info.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SOFT),
        ("BOX", (0, 0), (-1, -1), 0.6, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))

    # --- Revni ak retni: yon sèl tablo, 3 kolòn ---
    rows: list[list] = []
    styles: list[tuple] = []

    def section(title: str):
        rows.append([P(title.upper(), s_bold), P(L["rate"], s_right), P(f"{L['amount']} ({cur})", s_right)])
        styles.append(("BACKGROUND", (0, len(rows) - 1), (-1, len(rows) - 1), SOFT))
        styles.append(("LINEBELOW", (0, len(rows) - 1), (-1, len(rows) - 1), 0.6, LINE))

    def line(label: str, amount: int, rate: str = "", minus: bool = False, strong: bool = False):
        text = ("−" if minus and amount else "") + _money(amount, lang)
        st = ParagraphStyle("amt", parent=s_bold if strong else s_body, alignment=TA_RIGHT,
                            textColor=RED if minus and amount else INK)
        rows.append([P(label, s_bold if strong else s_body), P(rate, s_right), Paragraph(escape(text), st)])
        if strong:
            styles.append(("LINEABOVE", (0, len(rows) - 1), (-1, len(rows) - 1), 0.6, LINE))

    section(L["earnings"])
    line(L["base"], doc.base_amount)
    if doc.overtime_amount:
        line(L["overtime"].format(h=_hours(doc.overtime_hours, lang)), doc.overtime_amount)
    if doc.bonus_amount:
        line(L["bonus"], doc.bonus_amount)
    line(L["gross"], doc.gross_amount, strong=True)

    section(L["deductions"])
    line(L["iri"], doc.tax_amount, minus=True)
    if doc.supplemental_tax_amount:
        line(L["supplemental"], doc.supplemental_tax_amount, _pct(doc.supplemental_rate), minus=True)
    line("ONA", doc.ona_amount, _pct(doc.ona_rate), minus=True)
    line("OFATMA", doc.ofatma_amount, _pct(doc.ofatma_rate), minus=True)
    if doc.cfgdct_amount:
        line("CFGDCT", doc.cfgdct_amount, _pct(doc.cfgdct_rate), minus=True)
    line("FDU / CAS", doc.fdu_cas_amount, _pct(doc.fdu_cas_rate), minus=True)
    if doc.other_deductions:
        line(L["other"], doc.other_deductions, minus=True)
    total_ded = (doc.tax_amount + doc.supplemental_tax_amount + doc.ona_amount + doc.ofatma_amount
                 + doc.cfgdct_amount + doc.fdu_cas_amount + doc.other_deductions)
    line(L["total_ded"], total_ded, minus=True, strong=True)

    amounts = Table(rows, colWidths=[width * 0.58, width * 0.14, width * 0.28])
    amounts.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 0.6, LINE),
        *styles,
    ]))

    # --- Net ---
    s_net_l = ParagraphStyle("netl", fontName="Helvetica-Bold", fontSize=12, leading=15, textColor=colors.white)
    s_net_r = ParagraphStyle("netr", parent=s_net_l, fontSize=15, leading=18, alignment=TA_RIGHT)
    net = Table([[P(L["net"], s_net_l), P(f"{_money(doc.net_amount, lang)} {cur}", s_net_r)]],
                colWidths=[width * 0.55, width * 0.45])
    net.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))

    # --- Peman ---
    if doc.status == "paid":
        state = L["status_paid"].format(date=_date(doc.paid_on))
    elif doc.status == "approved":
        state = L["status_approved"]
    else:
        state = L["status_draft"]
    pay = Table([[P(L["payment"], s_small), P(_payment_text(doc, L), s_bold), P(state, s_right)]],
                colWidths=[width * 0.16, width * 0.5, width * 0.34])
    pay.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    story = [
        head, Spacer(1, 8 * mm),
        info, Spacer(1, 7 * mm),
        amounts, Spacer(1, 5 * mm),
        net, Spacer(1, 6 * mm),
        pay,
    ]

    generated = L["generated"].format(date=_date(doc.generated_on))
    is_draft = doc.status == "draft"

    def on_page(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(MUTED)
        canvas.drawString(18 * mm, 12 * mm, generated)
        canvas.drawRightString(letter[0] - 18 * mm, 12 * mm, "konmbit.com")
        if is_draft:
            canvas.setFont("Helvetica-Bold", 70)
            canvas.setFillColor(colors.Color(0.86, 0.15, 0.15, alpha=0.10))
            canvas.translate(letter[0] / 2, letter[1] / 2)
            canvas.rotate(35)
            canvas.drawCentredString(0, 0, L["watermark"])
        canvas.restoreState()

    buf = BytesIO()
    SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=18 * mm, bottomMargin=20 * mm,
        title=f"{L['title']} — {doc.employee_name} — {doc.period_name}",
        author=doc.org_name, creator="KONMBIT",
        pageCompression=1 if compress else 0,
    ).build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()